
db.jdbc.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;TRACE_LEVEL_SYSTEM_OUT=2
db.driver.class=org.h2.Driver
db.username=sa
db.password=
hikari.max.pool.size=10
hikari.min.idle=3
hikari.idle.timeout=3